name: Test Flask API

# Cuándo se ejecuta el workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Trabajos a realizar
jobs:
  test-api:
    runs-on: ubuntu-latest # Usamos un runner con Ubuntu

    steps:
      # 1. Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Puedes cambiar la versión si prefieres otra

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask  # Instalamos Flask directamente (o usa requirements.txt)

      # 4. Ejecutar la API en segundo plano
      - name: Start Flask API
        run: |
          python app.py &  # Ejecuta la API en segundo plano
          sleep 5  # Espera 5 segundos para que la API esté lista
